### ISSUE TITLE
[PROPOSAL] Sunflower Land Team Revenue

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#188] opened 2022-01-25 20:44 UTC
The purpose of this proposal is to discuss a mechanism that will enable the creators of Sunflower Land to receive funds to build the project.

The game has been bootstrapped completely by open source developers **without any funding**. To reach our true vision and create the future of the MetaVerse the team will obviously need a line of revenue to support building the game and the community. 

The goal of this proposal is to find a means to produce a revenue which would be used to build out the vision for the game and incentivise contributors. We are a community project, and open source all proposals for community consensus. Please be respectful of those sharing their ideas.

The metrics below are based on acquiring an initial reserve to build the game out. Once the team has sufficient funds a more farmer friendly model can be adopted.

**Expenses**

- Launch costs are around 10-20K
- Infrastructure costs will be roughly 10K monthly (depending on players)
- Legal + Miscellaneous costs will certainly arise at some point
- We will need at least 8-10 full time employees to build the next milestones in the project (New resources + the creator economy - community crafting where you can launch your own NFTs, tools and resources)

## $1 MATIC to play

When creating a farm, players will be required to donate 1 MATIC - 10% would go to a charity of your choice and the rest to the Sunflower Team.

**Pros** 👍 

- Team will receive funding from the start to cover operating costs
- Disincentives bot/skim farmers from creating multiple accounts at a low cost

**Cons**  

- 1 MATIC to play

## Withdraw Fee

When withdrawing resources from your farm to your wallet, a withdraw fee would be taken. This will be used to fund the project and support future features like the **Wishing Well Liquidity Pool**. https://github.com/sunflower-land/sunflower-land/issues/207

Note: These fees are likely to reduce once the team has built a reserve of funds to build the project. The team will not raise fees at any point unless the community votes and agrees on it.

- Less than 10 SFL - 30%
- Less than 100 SFL - 25%
- Less than 1000 SFL - 20%
- More than 1000 SFL - 15%
- More than 5000 SFL - 10%

**Pros** 👍 

- Players are encouraged to hold and use the tokens on their farms
- Farm skimmers (people playing at low margins only to sell the token) are taxed higher than loyal and good players
- Team can use the SFL token for features, liquidity providing or other means
- Players encouraged to build up their empire on one account, instead of multi-accounting
- Once you have the token, you can swap/transfer it as many times as you want without being taxxed. 

**Cons** 

- Players need to factor in the withdraw tax to any sort of ROI they develop.

## Transaction Fee - $0.1 Fee

In Sunflower Land, players can decide when to sync their data on chain. We anticipate a user would sync to the Blockchain every 1-3 days. Each transaction incurs an operating cost that architecture must support and the team must pay for.

When transferring or withdrawing data from the Blockchain, include a flat 0.1 MATIC fee.

Note: This fee does not apply to saving your farms progress. It only applies when you wish to transfer your assets on-chain.

## Open Sea Royalties

Add a royalty fee onto NFTs that are traded on secondary markets. For instance, on Open Sea items apply a **10%** on all sales which goes to the teams wallet. 

# Vote

Thanks for taking the time to read this proposal.

Vote using the 👍  or 👎  emoji.

**Comment by AncientHorse** [comment] 2022-01-26 06:27
I support this idea and like the fact a premine could be avoided.

**Comment by silici0** [comment] 2022-01-26 11:55
Since we love the transparency, i would says that since we could check fee rate and the wallet is receiving that fee, everything will be ok.
The major problem is that with the token variation price, it maybe hard to control the necessary amount on monthly bases.

On the future lets say that wallet is super health, you always can use fee to burn and control economy.

**Comment by adamhannigan** [comment] 2022-01-26 14:00
> Since we love the transparency, i would says that since we could check fee rate and the wallet is receiving that fee, everything will be ok. The major problem is that with the token variation price, it maybe hard to control the necessary amount on monthly bases.
> 
> On the future lets say that wallet is super health, you always can use fee to burn and control economy.

Definitely. Once the wallet gets healthy and a DAO is formed these sort of ventures would be achievable. The team and community can decide what would be best for the projects health and where the funds can go.

This fee could go to 0 or it could remain and fund other areas in the project such as the idea you mentioned :)

**Comment by Pranav-yadav** [comment] 2022-01-26 14:16
Taxing token buyers instead of Players seems the best approach.
I support the proposal of Token Sale Fee 👍

**Comment by defido** [comment] 2022-01-26 23:14
I totally support a tax mechanism on the token if you put that into place. It's the best way to get instant funding from the buy & sell of the token.

2% is too low though, I would suggest 6-8%. That makes sure at the start you can fund your project. Then once you become more successful, it can be lowered.

**Comment by zeldamajora** [comment] 2022-01-27 10:46
as a player i don't mind to be taxed 2% for swapping my hard earn Sunflower Land Token knowing i'm contributing to build this awesome game.so yeah for the fee as a buyer or seller .
a 2% as a buyer and let's say 2% or 1% as a player

**Comment by adamhannigan** [comment] 2022-01-27 13:24
@defido That is a good point, going up will cause a lot of issues. We can always go down.

Perhaps a **5%** fee is a good middle ground here.

**Comment by defido** [comment] 2022-01-27 13:44
> @defido That is a good point, going up will cause a lot of issues. We can always go down.
> 
> Perhaps a **5%** fee is a good middle ground here.

I will happily ape into 10%+ coins, and have so very often. If your project is rocking even 10% doesn't bother me. Clifford_inu has a 15% sell. It hit 100M MC in one day.

You guys smashed it last time, if you hit that scale again, rewarding the community by going down is great. But yeah, going up, always unhappy customers.

5% is fine, but honestly if you said 10%, but 5% of that goes directly into development/team and 5% into marketing/whatever else is needed. I wouldn't bat an eye. 

I personally think 5% isn't enough, but it's a team decision. These things cost real money to run.

**Comment by Rofrtd** [comment] 2022-01-27 21:43
@defido good points here! 
Lowering the tax is always welcome. Thanks for your feedback!

**Comment by adamhannigan** [comment] 2022-01-27 22:15
The other approach we can take is that we tax sells and not buys.

This would encourage people to hold onto their tokens and encourage new people to join the community and hold.

**Comment by Rofrtd** [comment] 2022-01-27 22:33
> The other approach we can take is that we tax sells and not buys.
> 
> This would encourage people to hold onto their tokens and encourage new people to join the community and hold.

Yeah I think is a good option too, but this would tax all the players rather then the Buyers only! 
But would definitely encourage people to hold.

**Comment by defido** [comment] 2022-01-27 22:33
> The other approach we can take is that we tax sells and not buys.
> 
> This would encourage people to hold onto their tokens and encourage new people to join the community and hold.

Tax buys a little, otherwise they buy and never sell and you're in the same problem of a lack of funds to fund the project. Selling you could set a different rate. 

It's like giving someone an iPhone to use from the Apple store and then only getting the money back in 2 years when they sell it. 

You actually shift the funding burden into yourselves and have to fund it yourselves just to keep up with demand. The more you grow, the more it costs, but you made $0 as people were onboarded. 

The idea would be that they play the game and make back the taxes, just like any real world taxation.

**Comment by Rofrtd** [comment] 2022-01-27 22:36
> > The other approach we can take is that we tax sells and not buys.
> > This would encourage people to hold onto their tokens and encourage new people to join the community and hold.
> 
> Tax buys a little, otherwise they buy and never sell and you're in the same problem of a lack of funds to fund the project. Selling you could set a different tax rate, which is becoming common.
> 
> It's like giving someone an iPhone to use from the Apple store and then only getting the money back in 2 years when they sell it.
> 
> You actually shift the funding burden into yourselves and have to fund it yourselves just to keep up with demand. The more you grow, the more it costs, but you made $0 as people were onboarded.
> 
> The idea would be that they play the game and make back the taxes, just like any real world taxation. It's a farm, farms pay taxes. Assets cost money to buy, yada yada.
> 
> These are just my thoughts, the only ones that can know if they can sustain the server & people costs, will be yourselves :D

And we can use the same idea "We can always lower the tax" in the future if needed.

**Comment by defido** [comment] 2022-01-27 22:38
> > > The other approach we can take is that we tax sells and not buys.
> > > This would encourage people to hold onto their tokens and encourage new people to join the community and hold.
> > 
> > 
> > Tax buys a little, otherwise they buy and never sell and you're in the same problem of a lack of funds to fund the project. Selling you could set a different tax rate, which is becoming common.
> > It's like giving someone an iPhone to use from the Apple store and then only getting the money back in 2 years when they sell it.
> > You actually shift the funding burden into yourselves and have to fund it yourselves just to keep up with demand. The more you grow, the more it costs, but you made $0 as people were onboarded.
> > The idea would be that they play the game and make back the taxes, just like any real world taxation. It's a farm, farms pay taxes. Assets cost money to buy, yada yada.
> > These are just my thoughts, the only ones that can know if they can sustain the server & people costs, will be yourselves :D
> 
> And we can use the same idea "We can always lower the tax" in the future if needed.

Tax is 10%, community outrage and then OK, 'we lowered taxes'. 

Tax is 0%, we're changing it to 10%, COMMUNITY RAGE. 

Don't worry about taxes, focus on the game play and things, the more that goes into that, the less anyone cares about % this or % that.

**Comment by Synedes** [comment] 2022-01-27 22:57
I loved the idea as I have another one, you can add a donation (as in v1 where we donated to other institutions) but a donation that we do for the project itself.

**Comment by Rofrtd** [comment] 2022-01-27 23:02
> I loved the idea as I have another one, you can add a donation (as in v1 where we donated to other institutions) but a donation that we do for the project itself.

As in another option for donations, still have the NGOs and SFL as donation options.

**Comment by spencerdezartsmith** [comment] 2022-01-28 00:14
> > The other approach we can take is that we tax sells and not buys.
> > This would encourage people to hold onto their tokens and encourage new people to join the community and hold.
> 
> Tax buys, otherwise they buy and never sell and you're in the same problem of a lack of funds to fund the project. Selling you could set a different tax rate, which is becoming common.
> 
> It's like giving someone an iPhone to use from the Apple store and then only getting the money back in 2 years when they sell it.
> 
> You actually shift the funding burden into yourselves and have to fund it yourselves just to keep up with demand. The more you grow, the more it costs, but you made $0 as people were onboarded.
> 
> The idea would be that they play the game and make back the taxes, just like any real world taxation. It's a farm, farms pay taxes. Assets cost money to buy, yada yada.
> 
> I think you'll find the players will get pretty clever and start making spreadsheets and tax tools to know how to still make a profit. Of which they still will.
> 
> These are just my thoughts, the only ones that can know if they can sustain the server & people costs, will be yourselves :D

Yep I agree with this. Taxing the buys makes more sense. The more the game grows the more the funding grows the better the game gets. Repeat 😄

**Comment by adamhannigan** [comment] 2022-01-28 13:15
@defido @spencerdezartsmith @Rofrtd @silici0 @AncientHorse @Pranav-yadav @Synedes 

I have revised a few options on this Proposal including the 'Withdraw fee' and the 'NFT fee'.

After playing around with the tax fee approach it introduces a few problems:
- Liquidity providers are taxxed
- Players are encouraged to sell
- People will opt for centralised exchanges.

I'm leaning towards the Withdraw approach but would appreciated your thoughts. The 'Withdraw fee' is a mechanism which will favour loyal and long term players and people to farm on a single account. It also makes it much easier for newcomers and liquidity providers to swap the underlying token.

**Comment by Meowgikarp** [comment] 2022-01-28 15:14
1. Agree that a withdraw fee would work better - however, from the player perspective, I'm not sure if the smaller "investors/players" will cry foul because visually it looks like taxing the poor and allowing the rich to extract wealth easier. In addition, players with multiple accounts will be "taxed" when transferring SFL from one of their own account to another. For example if I have 3 accounts and I want to transfer my SFL to one "main account", I will need to pay the fee. This might actually be a good thing because it discourages multiple accounts. On the other hand, it also will cost more for me to withdraw the SFL to swap for other resources, such that I would rather use barter trade rather than use SFL. 

2. Another way is perhaps a locked SFL mechanism, similar to Defi Kingdoms. For example, at farm level 1, 90% SFL you gain from each harvest is inherently "locked" and cannot be withdrawn. The locked SFL will only be gradually unlocked over time. However, you can still use locked SFL immediately to purchase in-game only items like NFTs and seeds and stuff, you just cannot cash it out directly. Also, the higher your farm level, the more % of your harvest are unlocked (e.g. lvl 5 farm = 70% of SFL of harvested plants are "locked", lvl 10 farm = 45% SFL "locked").  Certain NFTs might also allow a small number of SFL "unlocking" each day. This will incentivise players to build up their farm, enjoy the gameplay and be rewarded for it. It will also ensure that "bots" which manage to get through the checks cannot cash out immediately.

**Comment by Meowgikarp** [comment] 2022-01-28 15:20
Oh yes I also wanted to say that I fully support taxing of some form to ensure that the team is funded sufficiently to run the game, inject liquidity when required, as well as perform some airdrops/marketing stuff. These are important aspects of ensuring stability in the game. 

Keep up the good work Sirs !  

[ Discord nick- Train88 : p ]

**Comment by InuBakaBo** [comment] 2022-01-28 16:55
Glad you like my withdraw fee suggestion!

**Comment by adamhannigan** [comment] 2022-01-28 18:44
@Meowgikarp The locked SFL sounds like a really nice idea. 

This is something I would like to explore, but will be a bit too much work to implement for our launch date.

**Comment by InuBakaBo** [comment] 2022-01-28 18:57
Yes I agree with @Meowgikarp, the locked token system is another mechanic that I have seen been implemented on multiple different games/projects

**Comment by AncientHorse** [comment] 2022-01-29 04:09
Just an idea and I'm not sure if it's technically possible.  What if instead of the burn pool being at Quickswap, Sunflower Land had its own uniswap based pool and all the fees went to the devs?  This has a couple benefits:

1) There would be no increased sell pressure on SFL.  Whether someone is buying or selling, a small fee goes to devs (albeit smaller than 5% but with a much much higher volume).  
2) When SFL is sold, it would only be sold 50% in volume because of the paired token could also be sold (wmatic, dai, etc.).

Players could still choose to shop around for best exchange rate but the game could provide a link to Sunflowerland pool by default.  Apologize if this is a silly idea and I know that would be another huge piece to code prior to launch day.

**Comment by defido** [comment] 2022-01-29 04:31
The

> @defido @spencerdezartsmith @Rofrtd @silici0 @AncientHorse @Pranav-yadav @Synedes
> 
> I have revised a few options on this Proposal including the 'Withdraw fee' and the 'NFT fee'.
> 
> After playing around with the tax fee approach it introduces a few problems:
> 
> * Liquidity providers are taxxed
> * Players are encouraged to sell
> * People will opt for centralised exchanges.
> 
> I'm leaning towards the Withdraw approach but would appreciated your thoughts. The 'Withdraw fee' is a mechanism which will favour loyal and long term players and people to farm on a single account. It also makes it much easier for newcomers and liquidity providers to swap the underlying token.

The CEX issue is only short term, it's not likely to list on a major exchange very soon, and in that time, the taxes raised could fund months, then they can be turned off again anyway. Which is where in game sales taxes or 'touching the metamask sell button' come into play. Such as a small MATIC fee for every time you harvest.

As well as selling upgraded farms and other things for in game revenue. 

The buy/sell tax is only short term, until the game matures and the in game sales can compensate. At least I think so.

**Comment by adamhannigan** [comment] 2022-01-29 10:59
@AncientHorse Great idea! But a lot of effort for our launch 😅 An in-game Auction house mechanic will appear one day which is better rates to and facilitates swapping of in-game items and resources

**Comment by adamhannigan** [comment] 2022-01-29 11:02
@defido Great points.

It definitely is the frame we need to look at this problem - What is a short term solution that can fund the startup of the game and give us 6-12 months of development.

The game will largely turn into an NFT creator economy game and that is where we will make the revenue.

**Comment by defido** [comment] 2022-01-29 11:05
> @defido Great points.
> 
> It definitely is the frame we need to look at this problem - What is a short term solution that can fund the startup of the game and give us 6-12 months of development.
> 
> The game will largely turn into an NFT creator economy game and that is where we will make the revenue.

Taxing helped SAFEMOON & BABYDOGE scale, then SAFEMOON went down and still survives. I honestly think make it 10% flat and make it simple. You can always change it later, and as you say, you're an NFT game in the end. This is a short solution and 10% is fair. I actually don't hear many complaints in the BDC community about 10%.

**Comment by adamhannigan** [comment] 2022-01-29 11:15
@defido Do you have any examples of the source code used for these mechanisms? My understanding of the SafeMoon model is that the tax is reflected amongst the holders, and liquidity is burnt (not sent to the developer team).

Both of these models rely on:
1. Team is incentivised by a huge pre-mine
2. The team is providing significant liquidity (SafeMoon excludes themselves as LPs from this tax)

Introducing a tax could discourage liquidity providers. Similar to Sunflower Farmers, it will be the community that provides the LP.

**Comment by defido** [comment] 2022-01-29 11:22
> @defido Do you have any examples of the source code used for these mechanisms? My understanding of the SafeMoon model is that the tax is reflected amongst the holders, and liquidity is burnt (not sent to the developer team).
> 
> Both of these models rely on:
> 
> 1. Team is incentivised by a huge pre-mine
> 2. The team is providing significant liquidity (SafeMoon excludes themselves as LPs from this tax)
> 
> Introducing a tax could discourage liquidity providers. Similar to Sunflower Farmers, it will be the community that provides the LP.

You can take a look at the OSS contract we are working for projects to launch with, it has single contract address and we are working with a bridge to be the first permissionless bridge. 

BUT, it has reflections, burns, wallets etc.

BDC holders have over $100,000,000 in liquidity locked I think. They will stake it, if it's worth it. 

If you're new to reflections as a holder, you'll find it doesn't discourage anyone from staking/holding. But it surely fattens the holders wallets and they love joking about it.

https://github.com/defido/DefidoContractForGood/blob/main/contracts/Token.sol

**Comment by adamhannigan** [comment] 2022-01-29 11:26
@defido Thanks for sharing, this is extremely useful. One concern with this approach is that it adds a lot of complexity to our ERC20 token. The testing/auditing required would likely stretch out our release date - given that most of our focus is on designing the game itself (not the token).

**Comment by defido** [comment] 2022-01-29 11:31
> @defido Thanks for sharing, this is extremely useful. One concern with this approach is that it adds a lot of complexity to our ERC20 token. The testing/auditing required would likely stretch out our release date - given that most of our focus is on designing the game itself (not the token).

Do you mean adding just the buy/sell tax? That's just the UNIROUTER setup, which has been audited 1000x times as it was forked mostly from SAFEMOON V2 contract, which passed CERTIK. 

But yeah I understand that theres a difficulty between "we need money pretty soon" and "we make money from in game items". 

In that case, just taxing the in game player whenever they interact with their wallet for a transaction is the absolute easiest. It's like a CC payment in that case. 1% of every transaction + 30 cents etc etc

**Comment by adamhannigan** [comment] 2022-01-29 11:50
@defido The tax on the transaction definitely would be the quickest development approach.

Some numbers:

We have 50,000 beta sign ups. Conservatively, let's expect we have 10,000 on launch day. Each player will save once to the blockchain per day. Given a 20 cent fee, this will earn the project 2,000 USD per day. 

At a minimum, we would need to earn around 5,000 USD to support building out a team.

We could consider taxing more heavily on the withdraw functionality. I.e. if you are withdrawing 1000 SFL (and the rate is 1SFL-1USD) you would be taxed up to 10USD (assuming you were going to sell on an exchange anyway)

**Comment by zeldamajora** [comment] 2022-01-29 12:20
i suggest to go for withdraw fees and transaction fees  and adding donation to the dev team like in v1 with charities ( this donation for every account old and new ones ) to boost the reserve initialy

**Comment by RogGarcia** [comment] 2022-01-29 16:01
It might be interesting, in addition to the possible fees (I agree with all of them), some kind of spontaneous financing, within the mechanics of the game. If the reward chest is still in V2, instead of redeeming it, we could donate the value contained in it to the development of the game, in exchange we would receive a non-tradable token, which would be necessary to craft unique NFTs to be released in the future.

**Comment by adamhannigan** [comment] 2022-01-29 17:54
@zeldamajora What do you think people would be willing to pay? 1 MATIC sounds reasonable - 0.1 Charity donation included

**Comment by AncientHorse** [comment] 2022-02-04 03:05
> @zeldamajora What do you think people would be willing to pay? 1 MATIC sounds reasonable - 0.1 Charity donation included

Honestly, this is more than reasonable.  I support it 100%.

**Comment by noprudhon** [comment] 2022-02-04 08:46
> @zeldamajora What do you think people would be willing to pay? 1 MATIC sounds reasonable - 0.1 Charity donation included

Very reasonable indeed, considering the cost of most of the P2E out there, that's virtually nothing as an entry level, yet it can benefits you (and us in the long run, since you'll have more funds to make a better game). I also support it 100%.

**Comment by stevewoody82** [comment] 2022-02-05 01:12
I like the idea of a max cap offchain. So at the end of 24 hours prompt to save, after 3 days prompt to save again, after a week force to save. 

Also if resources reach a threshold prompt to save, if they exceed that threshold by a % then force to save. This will stop any shock mints hitting the blockchain that can derail the economy.

**Comment by stevewoody82** [comment] 2022-02-05 01:15
I think the donation to charity should be 25% - It feels like a better number and 0.25 Matic per player is still lower than the 0.3 that you recommended in the first version.

25% charity
50% operations cost
25% future growth

**Comment by zeldamajora** [comment] 2022-02-05 14:18
> lower

i think that for a start 0.1matic  charity donation is good after a certain period it can be raised to 0.25 ....be sure that if the game has the needed budget it will continue to fund charities more and more but if not and the money goes elsewhere the developement of the game will get slower and that's what we try to avoid here...so to resume here : funds for the projects first and then charities

**Comment by adamhannigan** [comment] 2022-02-05 18:27
@stevewoody82 Great to see your face pop up in the Github issues 💪 

20-30% is where I want to see the donations going. Based on some other comments, it seems easier to reduce the funds going to devs instead of increasing them. Starting at 10% means we can always go up if the project is financially fit. If you initially give too much to charity and cannot finance the project it will be a bit tougher to take the money away from the charity donations (at least I would feel unethical about doing that 😓 )

**Comment by silici0** [comment] 2022-02-05 18:52
Looking in the NFT games, they having removing stakes, starting using FEE to pool and burn. 
Keeping in mind that fee can be at different percents accordingly with amount that user hold or how long the player is holding.
For example, withdraw in the first week will have 20% fee than 15%, after 2 weeks 10%.. with mechanics like that you can increase LP, burn to keep price healthy.
Another example is how much you hold will increase or decrease fee rate..

Maybe NFT crafting shoud reward creator, LP, devs pool and burn some tokens ;)

**Comment by Ramtin9** [comment] 2022-02-05 21:47
Idk if it has been suggested before or not, you guys should add an in-game charity tap to pay any amount of Metic or SFL, for players who want to volunteer and help the team (apart from the initial 1 metic).

**Comment by adamhannigan** [comment] 2022-02-06 12:33
@Ramtin9 Yes, we want to gamify donations and give the player something in return! I.e. to access something to that chops down trees faster you would need to donate to a deforestation charity. To collect water, you need to donate to the charity project.

In these cases we would want majority of proceeds to go to the Charity ❤️

**Comment by stevewoody82** [comment] 2022-02-06 23:35
Some comments in the Ambassador chat are talking about how it shouldn't be called a donation anymore as it's not all going to charity. Rather a *fee

This made me think about a narative where a popup at the start - builds the lore around the Goblins. 


Goblins have taken over your farm ... 
They are willing to let you take back ownership but you need to talk to them first.
Click to continue


(Pay 1 Matic to get control of your farm)

Goblin Leader
WTF You gonna do about it .... Pay me !


Reason - If you can make people laugh, they might overlook a one time fee, also it sets the tone with the lore around the gobins. There could also be a read more icon that explains the breakdown of the cost.

**Comment by percusshon** [comment] 2022-02-09 20:52
Will the SFL required for withdrawal fees be reduced when the half-life is reached?

**Comment by adamhannigan** [comment] 2022-02-09 20:55
@percusshon Over time we will adjust this based on the difficultly it takes to earn that much SFL. 

In the future when it takes a week to earn 10 SFL (for example), the tax would likely be lessened so it does not impact players who worked hard

**Comment by TA418** [comment] 2022-02-09 20:57
I think overall this is a smart approach to this issue. I also stand behind the fact that devs should be paid for their hard work in some way. I would like to offer one suggestion, the ability to donate either MATIC or SFF to the project from within the game. Completely optional but a way to help support the devs.

Can't wait to get in!

**Comment by arianebrandao** [comment] 2022-02-09 21:01
I can't agree with the "Withdraw Fee" values, they are very high. Maybe lower a bit the quantity of SLF required for the percentage and allow 0%-2% in the minimum percentage.

**Comment by PapyMax** [comment] 2022-02-09 21:06
Hi,

I am ok if you give me a golden cauliflower :)

Nooo, let me play for ever your game will be enough !
And this seems a good point to make the game live longer so I am totaly agree with that !
And more, we are more creative when we can focus without thinking about money

So hope most people will accept your proposal !

May the cauliflower be with you !

**Comment by gavinrickard** [comment] 2022-02-09 21:23
seems like a great idea to me :)

**Comment by Gtillman** [comment] 2022-02-09 21:33
I love the revenue proposal. One additional thing that could be made I think is the opportunity to donate to the causes you have more than once. Maybe just as a button somewhere rather than a prompt. So that way we can donate more later on if we want to. You can take a percentage of that donations.

**Comment by Protocteur** [comment] 2022-02-09 21:49
I'm mostly fine with everything but i suggest some more toughts about 2 things :

1/ First is the team revenues, paying team with MATIC is fine, but recently crazyminder (and others projects) got shutdown by the team. For crazyminers, team was paid in BNB on Minting and had no difficulty to shutdown at the first dump of the token, because shutting down the project had no financial consequences at all for them. I think that was an easy tought for them, shutdown the project that became too hard for them and keep all earning ? Most of people would do this for sure, no matter their first tought/motivation at the begining of a project.

But as a developer i think you need to be paid in MATIC but as a player/investor, i'd like the team to choose a ceiling amount. And over the ceilling of revenue those matic are used to buy SFL, that are locked for 6 months (relative to the date of the bought). This create a bonus pool for your continuous success (and so only for the success ..) This way you can't shutdown the project without loosing a lot with us (and get a fair wage for your work because it only impact the bonus). 

I also think this pool should be used to keeping market stable (burning a part of the pool in case of hard down on the price, and sale it without waiting for the unlock if the price goes too high)

Saling when price is too high may help new investor to enter at a fair price, and reduce the risk for FOMO to loosing too much money if then the price getting low. This way it's fair for new and old player to play, and for the team that succeed even more that expected.

This way, if the game succeed, team will get a recurring bonus with 6 month of delay, if the game get so good that the price is exploding, the team get a special reward/bonus immediatly, and the game keep a stable economy. This also would create more trust for everyone.

And obviously this has to be corelated with halving.

2/ I spoiled a bit, but withdraw fee should to be corelated with halving too ;)

**Comment by hooman8897** [comment] 2022-02-09 21:54
The sunflower team must have income from the game, otherwise it is not acceptable, but it is much better when they receive this income little by little and slowly from the players.
This way, any player can join the game with any amount of budget he has, and after his first withdrawal, with the little capital he has invested in the game, he can invest more capital with great confidence in the game and the project.👍👍👍👍👍🙏🙏🙏🙏🙏🙏🙏🌷🌷🌷🌷🌷🌷🌷🌷

**Comment by Ant-Redstone** [comment] 2022-02-09 21:57
I love all the suggestions except the withdraw fee, it kinda scares me that u consider ppl to withdraw 1000-5000 tokens at once, it would be how long holding the tokens to reach it in your maths and what's the reason to someone hold it and not put any liquidity or something like that, but hold in-game without withdraw? I would be happier with a stake system than that

**Comment by hooman8897** [comment] 2022-02-09 21:57
The importance and growth of sun flower was that all players with very low budgets could earn money. I hope this policy will be repeated correctly in version 2.

**Comment by RubenRamirez07** [comment] 2022-02-09 23:39
I love all the proposals and I agree with all of them, my only question is whether to donate the entire matic for each of the farms in which we have invested in v1?

**Comment by mekhox** [comment] 2022-02-09 23:47
sunflower to the moon 🚀

**Comment by Gitgudjs** [comment] 2022-02-10 00:57
Do what Tank Battle is doing 5% selling fee, and read their whitepaper, do not mess it up SFF.

**Comment by iannono** [comment] 2022-02-10 00:57
I totally support, let's do it : )

**Comment by j923sneaks** [comment] 2022-02-10 01:32
> 2/ I spoiled a bit, but withdraw fee should to be corelated with halving too ;)

Agree with @Protocteur ! I think withdraw brackets should adjust w/ SFL minting too. I imagine new players won't be able to sustain themselves if they have small capital...

**Comment by javiertognarelli** [comment] 2022-02-10 02:21
I like these proposals seems reasonable to make an economy sustainable. Also it could be added make some pools for staking rewards and therefore diminishing supply

**Comment by kimberlite07** [comment] 2022-02-10 02:41
Hey @adamhannigan. Are the withdrawal fees final? I couldn't help but feel that the withdrawal fees are too high. Especially that jumping from one bracket to another is not as easy anymore considering the price at 1M.

Maybe we can tweak it a bit say 20, 17, 15, 13, 10?
Also, I can understand it when SFL is being withdrawn. However, how would this work if NFTs are the ones being withdrawn?

**Comment by adamhannigan** [comment] 2022-02-10 10:11
A few key points to remember about these withdrawal fees is that they:

1. Support building the game
2. Sustain the game with liquidity features

Both of these items naturally improve the game which leads to more traffic, more players and all your tokens, collectibles and resources becoming more valuable. The higher these fees are, the faster the game will grow 🚀

**Comment by yyuuttaaoo** [comment] 2022-02-10 11:31
The Withdraw Fee tax ratio is terrifying me. It is more than encouraging players to hold. This may discourage transaction and reduce trade volume. And it is one time. So maybe you won't be able to earn much. Why don't you create an exchange market or lottery pool inside the metaverse and deduct a proportional fee so that you can profit from active trading.

**Comment by Z1kou** [comment] 2022-02-10 14:54
Sorry i might be late to the party but i read most of the comments what i extracted is :

-Taxing transactions mostly withdrawing to encourage people to hold the token
-Taxing NFT's transaction.

the problems that we would face with this is either the taxes feel too high for the players or The Liquidity providers  ( I dont feel like personally thats a problem because the entry fee of the game is already too low id rather have a higher entry fee if it means ensuring the projects longetivity)


What i would suggest : Adding a limited edition funding crowd  for the project funding with some limited time rewards that dont need to be too flashy its just to show us that we believed in the project since the start ! 

-the fund crowding should be annouced by the start of the beta since players would see the life of the project and ( lets 
be honest those who believe in the project wont even need a live beta to support I personally believe that).

-This would help with providing the initial money to lunch and fill up the games reserves way faster than relying on tax

-maybe disguise this crowd funding with a lunching carnaval in which we play games like find the easter egg in the map within this time limit . the first to give this items effect in the events chat wins to participate u pay 1 matic as an example there could be alot of ways around this

-Or this one which is my favorite why not utilise a storyline (The SunFlowerLand a utopia built by a community of farmers whose sole purpose in life is the growth of there crop and most importantly the growth of there community the still fetus like Land is endagered since before its official lunch by evil , an evil lurking in every corner of this world , an evil that is inevitable to face for this community to come forth ,The land has called you once and asked you for the patience to wait for its come back , Now The land is calling its community back to breath life into it and make it finally reach the corners of this world , and extend to the moon, The Land is in need of its community...Will you answer its calling?

**Comment by adamhannigan** [comment] 2022-02-10 18:55
@Z1kou Some great ideas 👏 

We will explore mechanisms like this in the future, but they require work and time we don't have at the moment (until we get more developers).

In terms of the pre-sale of items, I want to avoid these types of avenues. I think there are a lot of overhyped projects that are selling NFTs for money without even having a game. I would prefer that we release the game and the NFT at the same time. The industry needs less hype and actual gameplay 😅

**Comment by Ainz-69** [comment] 2022-02-12 12:13
you got my attention and my time, my hoping for the best in future

**Comment by InuBakaBo** [comment] 2022-02-13 22:02
I have concerns about the withdrawal tax as it seems quite high. As, if I were to deposit 1000SFL to help and put into the Liquidity Pool wishing well, then later down the road I remove it and want withdraw the SFL, I would be hit with (according to the current proposal) 15% withdrawl tax. Therefore it really isn't an incentivisation to put into the Liquidity Pool. Maybe if there was a tax exemption/alternative for SFL that is deposited to use for the liquidity pool. Maybe create a way to distinguish between SFL that was farmed, and SFL that was deposited?

**Closed** 2022-02-14 11:38 UTC
Labels: proposal
