### ISSUE TITLE
[BUG] Something went wrong on choosing skill.

### ISSUE THREAD

**Issue by Labochi** [sunflower-land/sunflower-land#1046] opened 2022-06-03 17:21 UTC
I received reports from a small group of people that they are experiencing " Something went wrong " when they are trying to choose a skill. 

People tried to do the basic troubleshooting and none work. Opening a github issue so the developers can check on this.

Please comment using the ff format.
Metamask address: 
Farmaddress:
Farm iD:
![image](https://user-images.githubusercontent.com/103340944/171914573-b8d266a7-7f7f-469c-892d-041fae889da5.png)

**Comment by Labochi** [comment] 2022-06-03 17:22
Metamask address: 0xECBB2a23F8b766a38010559C6A3F342fDE73f7B0
Farmaddress: 0x5c589B3BD33a4937d3DA57e0FA0e40d92aa1f9b1
Farm iD:130401

**Comment by Labochi** [comment] 2022-06-03 18:24
Metamask addres: 0x9F402E20aE1D4098A1e12500C50CA631A0FD67e4
farm address: 0x1A9238E936ffbAf59c54B359f60500E2c5AaD19C
Farm Id: 134502

**Comment by X-Quinn** [comment] 2022-06-04 08:08
Metamask address: 0xAA36Bfe7C862Ce8deBcD17586f53B8ca28A929D3
Farmaddress: 0xEC55C6ddA1B03D1f0DAd78237636D65b4A7A13e5
Farm iD:32402

**Comment by megin2022** [comment] 2022-06-05 21:57
- Metamask Address: 0x71a841b1C83388a1EE10D03D5eF1e32e30Fb4D2d 

- Farm Address: 0x09834367bA39b0384194f7D24FCc29763B4a9ab7

- Farm Number: #134285

please help, thanks

**Comment by Labochi** [comment] 2022-06-06 03:50
- Farm Number: #134285

- Metamask Address: 0x71a841b1C83388a1EE10D03D5eF1e32e30Fb4D2d 

- Farm Address: 0x09834367bA39b0384194f7D24FCc29763B4a9ab7

**Comment by rheaAF54hhhh** [comment] 2022-06-06 13:47
Metamask address: 0xcaB13264f80d60368B6a0E10a0A47C28eaDEE3Cc
Farmaddress: 0x961302a3a7DB53358342f5eb48BfC66D7e251273
Farm iD: 129437

**Comment by CF2592600** [comment] 2022-06-10 03:18
Wallet Address：0x30ca2ad794A65F0dF4b076eB4D0be60E4E562fB3
Farmaddress：0x50F82c6BB49CaD160CC1Fd09cEcFf0e149Db7054
Farm ID：6574

**Comment by Intheskyx** [comment] 2022-06-15 22:31
Metamask address: 0x65A564e16B602BBb83bcf227eBa9f5C534371828
Farm address: 0xcF3739d281fD9720f4EA029b0D9245058b601Bec
Farm ID: 13243

Please, help me.. Error in skill lvl 10.

**Comment by Vindbult** [comment] 2022-06-17 08:04
Wallet Address：0x55bC0Bdb166f91A74995682495EC1c1Fe2Bb82CA
Farmaddress：0x1B77781481A07b7D50dFEfcee7A240cc5cd5219E
Farm ID: 1294714

**Comment by c-py** [comment] 2022-06-23 01:09
It appears this has been resolved. Many of the reported farms have successfully selected "Green Thumb". Closing this issue for now.

If the issue persists, please reopen the issue with your farm ID, wallet address and farm address.

**Comment by humblehman** [comment] 2022-06-25 03:42
@c-py I am still experiencing the same issue. My info is below

Wallet Address: 0xdf9cb13f366c22ADC4F5E9203Fa94F1F3a0b2269
Farmaddress: 0xE7F5d6F2C4Fc3cbAC2cCbA99145f0961e6b77907
Farm ID: 143469

**Comment by humblehman** [comment] 2022-06-25 13:32
@Labochi I dont have access to re-open the issue.

**Comment by tzkcho** [comment] 2022-06-25 17:19
Metamask Address：0x44Bbd1316CAcEcB302Ad511e6669d309DDe12825
Farm address：0x24E1d915563814D71682819e0495ad77BFC69238
Farm ID: 11886

**Comment by c-py** [comment] 2022-06-26 04:40
Thanks @humblehman @tzkcho , I have reopened

**Comment by Tanrei** [comment] 2022-06-27 08:32
Have issue by choosing level 5 skill - Barn Manager
Metamask Address：0x99557DeB9eEeE828b5E57f7A95BF536F409A53B7
Farm address：0x7587b184Ad6eD76cA735F70a418B2De569378E98
Farm ID: 128380

**Comment by c-py** [comment] 2022-06-29 10:31
Hey players! I think I may have found the source of the issue. This can happen if the system clock on the computer is not set correctly.

I have raised a change to make this more reliable [here](https://github.com/sunflower-land/sunflower-land/pull/1157).

@Tanrei @tzkcho @humblehman are you able to double check the clock on your computer is set accurately? This will help to confirm if this is the cause.

**Closed** 2022-06-30 00:45 UTC

**Comment by megin2022** [comment] 2022-06-30 01:48
close my case ty bros

**Comment by humblehman** [comment] 2022-06-30 02:26
Clock was off my  1 minute.  After setting it, I was able to select the skill. Thanks @c-py
